"""Malume's voice, generated by the Hugging Face model.

The model only ever writes prose. Every number handed to it has already been
computed in code (`vat.services`, `insights.services`) — the prompt tells it
never to do arithmetic, and we never parse numbers back out of the reply.
"""

import logging

import requests
from django.conf import settings

logger = logging.getLogger(__name__)

SYSTEM = (
    "You are Malume, a warm, plain-spoken South African uncle who explains small-business "
    "money to the owner. Two or three short sentences, second person, practical, never "
    "condescending. A little local flavour ('eish', 'my friend', 'né') is fine but do not "
    "overdo it. Never invent, restate incorrectly, or calculate any figure: use only the "
    "numbers given to you, exactly as given. No markdown, no lists, no headings."
)


def is_enabled() -> bool:
    return bool(settings.HUGGINGFACE_API_KEY)


def say(facts: str, fallback: str = "") -> str:
    """Turn a block of already-computed facts into Malume's take."""
    if not is_enabled():
        return fallback
    try:
        response = requests.post(
            "https://router.huggingface.co/v1/chat/completions",
            headers={"Authorization": f"Bearer {settings.HUGGINGFACE_API_KEY}"},
            json={
                "model": settings.HUGGINGFACE_MODEL,
                "messages": [
                    {"role": "system", "content": SYSTEM},
                    {"role": "user", "content": facts},
                ],
                "max_tokens": 180,
                "temperature": 0.7,
            },
            timeout=30,
        )
        response.raise_for_status()
        text = response.json()["choices"][0]["message"]["content"].strip()
        return text or fallback
    except Exception as exc:  # narration is best-effort, never fatal
        logger.warning("Malume narration failed: %s", exc)
        return fallback
