# Generated by Django 5.1.6 on 2026-08-01 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stated_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_status', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(choices=[('office_supplies', 'Office supplies'), ('transport', 'Transport'), ('food_and_entertainment', 'Food & entertainment'), ('utilities', 'Utilities'), ('software_and_subscriptions', 'Software & subscriptions'), ('stock_and_materials', 'Stock & materials'), ('professional_services', 'Professional services'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=40)),
                ('category_source', models.CharField(choices=[('ai', 'AI'), ('rule', 'Rule'), ('user', 'User')], default='rule', max_length=8)),
                ('payment_method', models.CharField(blank=True, max_length=60, null=True)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('edited', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='periods.period')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='uploads.upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=60)),
                ('before', models.TextField(blank=True, null=True)),
                ('after', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(default='user', max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ledger.transaction')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('probable_duplicate', 'Probable duplicate'), ('missing_required_field', 'Missing required field'), ('vat_mismatch', 'VAT mismatch'), ('line_item_total_mismatch', 'Line item total mismatch'), ('unusual_amount', 'Unusual amount'), ('large_cash_transaction', 'Large cash transaction'), ('recurring_subscription', 'Recurring subscription')], max_length=40)),
                ('label', models.CharField(max_length=160)),
                ('matched_transaction', models.UUIDField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('recommended_action', models.CharField(blank=True, max_length=200)),
                ('human_approval_required', models.BooleanField(default=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ledger.transaction')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'period'], name='ledger_tran_user_id_abe1af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='ledger_tran_user_id_ef9a94_idx'),
        ),
    ]
